spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.247.131:3306/community
    username: root
    password: 123456
    #指定数据源类型
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #配置初始化大小、最小、最大
      initial-size: 5
      min-idle: 10
      max-active: 20
      # 配置获取连接等待超时的时间（毫秒）
      max-wait: 60000
  #邮箱配置
  mail:
    host: smtp.qq.com
    port: 465
    username: 1543977012@qq.com
    password: nkxmiarxpnkxicih  #第三方客户端的授权码，不是qq邮箱的登录密码
    protocol: smtps
    properties.mail.smtp.ssl.enable: true #开启SSL
    default-encoding: utf-8
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
  type-aliases-package: com.atguigu.community.entity  #mybatis别名
  mapper-locations: classpath:mapper/*.xml   #加载 映射文件
#设置日志
logging:
  level:
    com.atguigu.community.Dao: debug

#community
community:
  path：
    domain: http://localhost:8080
server:
  port: 8080
  servlet:
    context-path: /community